version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:senha@db:5432/pgra?schema=public
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=pgra
    volumes:
      - pgra-data:/var/lib/postgresql/data

volumes:
  pgra-data: